import { StoreData } from '../../types/store';

export const generateStoreCSS = (storeData: StoreData): string => {
  const { settings } = storeData;

  return `
/* Generated by eStore Page Maker */

/* 1. CSS Variables & Core Setup */
:root {
  --bs-primary: ${settings.primaryColor};
  --bs-primary-rgb: ${hexToRgb(settings.primaryColor)};
  --bs-secondary: ${settings.secondaryColor};
  --bs-secondary-rgb: ${hexToRgb(settings.secondaryColor)};
  --bs-warning: ${settings.accentColor};
  --bs-warning-rgb: ${hexToRgb(settings.accentColor)};
  --bs-font-sans-serif: '${settings.fontFamily}', system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
  --custom-shadow: 0 10px 30px -15px rgba(0, 0, 0, 0.15);
  --custom-shadow-hover: 0 15px 35px -15px rgba(0, 0, 0, 0.25);
  --border-radius: 0.5rem;
  --transition-speed: 0.3s;
}

body {
  font-family: var(--bs-font-sans-serif);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  background-color: #fcfcfc;
}

/* 2. Typography & Global Styles */
.section-header h2 {
  color: var(--bs-primary);
}
.section-divider {
  height: 4px;
  width: 80px;
  background-color: var(--bs-warning);
  border-radius: 2px;
  margin-top: 1rem;
}
.line-clamp-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

/* 3. Header & Navigation */
.navbar-custom {
  transition: background-color var(--transition-speed) ease, box-shadow var(--transition-speed) ease;
}
.navbar-custom .nav-link {
  position: relative;
  transition: color var(--transition-speed) ease;
}
.navbar-custom .nav-link::after {
  content: '';
  position: absolute;
  bottom: 0;
  left: 50%;
  transform: translateX(-50%);
  width: 0;
  height: 2px;
  background-color: var(--bs-primary);
  transition: width var(--transition-speed) ease;
}
.navbar-custom .nav-link:hover,
.navbar-custom .nav-link.active {
  color: var(--bs-primary) !important;
}
.navbar-custom .nav-link:hover::after,
.navbar-custom .nav-link.active::after {
  width: 100%;
}
.cart-icon {
  transition: transform var(--transition-speed) ease;
}
.cart-icon:hover {
  transform: scale(1.1);
  color: var(--bs-primary);
}

/* 4. Hero Section */
.hero-section {
  min-height: 60vh;
  background-size: cover;
  background-position: center;
  position: relative;
}
.btn-cta {
  background-color: var(--bs-warning);
  color: #111;
  border-color: var(--bs-warning);
  padding: 0.8rem 2rem;
  font-size: 1.1rem;
  border-radius: 50px;
  transition: transform var(--transition-speed) ease, box-shadow var(--transition-speed) ease;
}
.btn-cta:hover {
  transform: translateY(-3px);
  box-shadow: 0 4px 15px rgba(0,0,0,0.2);
  color: #000;
}

/* 5. Product Card Styling */
.product-card {
  border: 1px solid #e9ecef;
  border-radius: var(--border-radius);
  overflow: hidden;
  box-shadow: var(--custom-shadow);
  transition: transform var(--transition-speed) ease, box-shadow var(--transition-speed) ease;
}
.product-card:hover {
  transform: translateY(-8px);
  box-shadow: var(--custom-shadow-hover);
}
.product-card-img-container {
  overflow: hidden;
  height: 250px;
}
.product-card-img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  transition: transform 0.5s ease;
}
.product-card:hover .product-card-img {
  transform: scale(1.05);
}
.product-card-title {
  color: #343a40;
  font-weight: 600;
  transition: color var(--transition-speed) ease;
}
.product-card:hover .product-card-title {
  color: var(--bs-primary);
}
.btn-add-to-cart {
  background-color: var(--bs-secondary);
  border-color: var(--bs-secondary);
  color: white;
  border-radius: 50px;
  font-weight: 500;
  padding: 0.4rem 1rem;
  transition: background-color var(--transition-speed) ease, transform var(--transition-speed) ease;
}
.btn-add-to-cart:hover {
  background-color: var(--bs-primary);
  border-color: var(--bs-primary);
  transform: scale(1.05);
  color: white;
}

/* 6. Why Choose Us Section */
.feature-item-card {
  background-color: #fff;
  border-radius: var(--border-radius);
  padding: 2rem;
  border: 1px solid #e9ecef;
  box-shadow: var(--custom-shadow);
  transition: transform var(--transition-speed) ease, box-shadow var(--transition-speed) ease;
  height: 100%;
}
.feature-item-card:hover {
  transform: translateY(-8px);
  box-shadow: var(--custom-shadow-hover);
}
.feature-icon {
  width: 60px;
  height: 60px;
  border-radius: 50%;
  background-color: var(--bs-primary);
  color: white;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: background-color var(--transition-speed) ease, transform var(--transition-speed) ease;
}
.feature-item-card:hover .feature-icon {
  background-color: var(--bs-secondary);
  transform: scale(1.1) rotate(10deg);
}

/* 7. FAQ Section */
.faq-accordion .accordion-item {
  background-color: #fff;
  border: 1px solid #e9ecef;
  border-radius: var(--border-radius);
  margin-bottom: 1rem;
  box-shadow: var(--custom-shadow);
  overflow: hidden; /* To keep border-radius */
  transition: box-shadow var(--transition-speed) ease;
}
.faq-accordion .accordion-item:hover {
  box-shadow: var(--custom-shadow-hover);
}
.faq-accordion .accordion-button {
  font-weight: 600;
  color: #212529;
}
.faq-accordion .accordion-button:hover {
  background-color: #f8f9fa;
}
.faq-accordion .accordion-button:not(.collapsed) {
  color: var(--bs-primary);
  background-color: #f8f9fa80;
  box-shadow: inset 0 -1px 0 rgba(0,0,0,.125);
}
.faq-accordion .accordion-button:focus {
  box-shadow: 0 0 0 0.25rem rgba(var(--bs-primary-rgb), 0.25);
  border-color: rgba(0,0,0,.125);
}
.faq-accordion .accordion-item:first-of-type,
.faq-accordion .accordion-item:last-of-type {
  border-radius: var(--border-radius);
}
.faq-accordion .accordion-item:first-of-type .accordion-button {
    border-top-left-radius: var(--border-radius);
    border-top-right-radius: var(--border-radius);
}
.faq-accordion .accordion-button::after {
  transition: transform var(--transition-speed) ease-in-out;
}

/* 8. Footer */
.footer-custom {
  background-color: #212529;
}
.footer-heading {
  color: var(--bs-warning);
  margin-bottom: 1rem;
}
.footer-links a {
  color: rgba(255, 255, 255, 0.7);
  text-decoration: none;
  transition: color var(--transition-speed) ease, padding-right var(--transition-speed) ease;
}
.footer-links a:hover {
  color: #fff;
  padding-right: 5px;
}
.footer-social-icon svg {
  transition: color var(--transition-speed) ease, transform var(--transition-speed) ease;
}
.footer-social-icon:hover svg {
  color: var(--bs-warning);
  transform: scale(1.2);
}

/* 9. Animations */
@keyframes fadeInDown {
  from { opacity: 0; transform: translateY(-20px); }
  to { opacity: 1; transform: translateY(0); }
}
@keyframes fadeInUp {
  from { opacity: 0; transform: translateY(20px); }
  to { opacity: 1; transform: translateY(0); }
}
.animate-fade-in-down {
  animation: fadeInDown 0.8s ease-out forwards;
}
.animate-fade-in-up {
  animation: fadeInUp 0.8s 0.2s ease-out forwards;
  opacity: 0;
}

/* Scroll-triggered animations */
.animate-on-scroll {
  opacity: 0;
  transform: translateY(40px);
  transition: opacity 0.6s ease-out, transform 0.6s ease-out;
}
.animate-on-scroll.is-visible {
  opacity: 1;
  transform: translateY(0);
}
`;
};

// Helper function to convert hex to RGB CSV
function hexToRgb(hex: string): string {
  let result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  if (!result) return '0,0,0';
  return [
      parseInt(result[1], 16),
      parseInt(result[2], 16),
      parseInt(result[3], 16)
  ].join(',');
}
